name: Firmware build on push

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Run PlatformIO
        env:
          VERSION: "0.0.${{ github.event.number }}"
        run: pio run

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: .pio/build/**/*.hex